<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rkw_projects"
 *
 * Auto generated by Extension Builder 2015-05-06
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'RKW Projects',
	'description' => 'Extension for handling projects',
	'category' => 'plugin',
	'author' => 'Steffen Kroggel',
	'author_email' => 'developer@steffenkroggel.de',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '7.6.11',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
			'extbase' => '7.6.0-7.6.99',
			'fluid' => '7.5.0-7.6.99',
			'rkw_basics' => '7.6.12-8.7.99',
			'rkw_authors' => '7.6.10-8.7.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);